require "shellwords"

# Queries the live HTCondor config of a running (or already-finished) annex
# pilot, straight from its own downloaded install under the session's
# staged_root -- never from the tarball's static annex.record and never
# from any system-wide HTCondor. This is the only reliable source of truth
# for values that can be silently overridden before annex.record's own
# value is ever applied, e.g. STARTD_NOCLAIM_SHUTDOWN via either
# ~/.condor/annex_config (a shell override sourced by annex-setup.sh) or
# ~/.condor/annex_pilot_config (an HTCondor config.d file copied in by
# annex-job-setup.sh, both real, supported customization points -- see
# USER-STEPS.md). Enumerating every possible override isn't reliable; only
# the live config system is.
#
# Assumes the OOD web server can both read staged_root (true by
# construction -- see template.html doc's staged_root) and execute the
# pilot's downloaded HTCondor binary directly. That binary was built for
# the compute node's OS/arch (detected via `uname`/`/etc/os-release` in
# annex-setup.sh, which itself runs on the compute node as part of the
# job -- see template/before.sh.erb), which may differ from the OOD web
# server's own OS/arch. Every method here is best-effort and returns nil
# rather than raising if that assumption doesn't hold.
module AnnexPilot
  module_function

  # PILOT_DIR is always `${staged_root}/pilot.<jobid>/condor-<version-arch-distro>`
  # (see the hpc.slurm generated by annex-setup.sh). Returns the first match
  # with a fully-assembled config (condor.sh present), or nil if the pilot
  # doesn't exist (yet, or ever, e.g. job hasn't started or failed early).
  def pilot_dir(staged_root)
    Dir.glob(File.join(staged_root.to_s, "pilot.*", "condor-*"))
      .find { |dir| File.exist?(File.join(dir, "condor.sh")) }
  rescue StandardError
    nil
  end

  # Queries a single HTCondor config value from the pilot located under
  # staged_root. Returns the raw string value, or nil on any failure
  # (missing pilot, missing binary, non-zero exit, wrong OS/arch, etc.) --
  # callers should validate the result themselves (e.g. before trusting
  # it's numeric).
  def condor_config_val(staged_root, option)
    dir = pilot_dir(staged_root)
    return nil unless dir

    config = File.join(dir, "condor_config")
    binary = File.join(dir, "bin", "condor_config_val")

    value =
      if File.exist?(config) && File.executable?(binary)
        `CONDOR_CONFIG=#{Shellwords.escape(config)} #{Shellwords.escape(binary)} #{Shellwords.escape(option)} 2>/dev/null`
      elsif File.exist?(File.join(dir, "condor.sh"))
        # Fall back to sourcing condor.sh itself in case the config file
        # isn't named condor_config in some future HTCondor release --
        # condor.sh is guaranteed to set CONDOR_CONFIG correctly regardless.
        `cd #{Shellwords.escape(dir)} && . ./condor.sh && condor_config_val #{Shellwords.escape(option)} 2>/dev/null`
      end

    value = value.to_s.strip
    value.empty? ? nil : value
  rescue StandardError
    nil
  end
end
